name: Integration tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - "samples/**"
      - ".github/workflows/pr-lint-samples.yml"
      - ".github/workflows/pr-lint.yml"
      - ".github/workflows/pr-unit-tests.yml"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 10
          - 12
          - 14

    runs-on: ${{ matrix.os }}

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - run: npm install
      - run: npm run test:integration
        env:
          VCAP_SERVICES: ${{ secrets.TENANT_CREDENTIALS_EU10_PLAYGROUND }}
