name: Lint SDK

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - "samples/**"
      - ".github/workflows/pr-lint-samples.yml"
      - ".github/workflows/pr-unit-tests.yml"
      - ".github/workflows/pr-integration-tests.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint SDK
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Lint SDK
        run: npm run lint
