name: Lint Samples

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "samples/**"
      - ".github/workflows/pr-lint-samples.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint samples
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./samples
      - name: Lint samples
        run: npm run lint
        working-directory: ./samples
