name: Library

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - "samples/**"
      - ".github/workflows/pr-samples.yml"

jobs:
  unit-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 10
          - 12
          - 14
    runs-on: ${{ matrix.os }}
    name: Unit test Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test

  integration-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 10
          - 12
          - 14
    runs-on: ${{ matrix.os }}
    name: Integration tests Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run integration tests
        run: npm run test:integration
        env:
          VCAP_SERVICES: ${{ secrets.TENANT_CREDENTIALS_EU10_PLAYGROUND }}

  lint:
    runs-on: ubuntu-latest
    name: Lint SDK
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Lint SDK
        run: npm run lint

  dependency-check:
    runs-on: ubuntu-latest
    name: Check SDK dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Run dependency check
        run: npm run checkDependencies
