name: PR Samples

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "samples/**"
      - ".github/workflows/pr-samples.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint samples
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./samples
      - name: Lint samples
        run: npm run lint
        working-directory: ./samples

  dependency-check:
    runs-on: ubuntu-latest
    name: Check samples dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./samples
      - name: Run dependency check
        run: npm run checkDependencies
        working-directory: ./samples

  sonarcloud:
    runs-on: ubuntu-latest
    name: Sonar Cloud Scan
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
